kind: Service
apiVersion: v1
metadata:
  name: prometheus-kafka-adapter-service
  labels:
    k8s-app: prometheus-kafka-adapter
spec:
  selector:
    app: prometheus-kafka-adapter
  ports:
   - name: web
     protocol: TCP
     port: 9201
     targetPort: 9201
